export const ADD="ADD";
export const REDUCE="REDUCE";
export const GET_TODO_REQUEST="GET_TODO_REQUEST";
export const GET_TODO_FAILUER="GET_TODO_FAILUER";
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS";
export const POST_TODO_SUCCESS="POST_TODO_SUCCESS";
export const POST_TODO_FAILUER="POST_TODO_FAILUER";